// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PT1OXxBIOKjSjlyrBZDKRhMzg6gT6Pw',
    appId: '1:375461501131:web:9f16f354949e50ccbfa34e',
    messagingSenderId: '375461501131',
    projectId: 'locallancers-app',
    authDomain: 'locallancers-app.firebaseapp.com',
    storageBucket: 'locallancers-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQdOvPb_NZBJ_DrLHcYu3lWQZpaHmRPh4',
    appId: '1:375461501131:android:bca449cf453186f1bfa34e',
    messagingSenderId: '375461501131',
    projectId: 'locallancers-app',
    storageBucket: 'locallancers-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvTNHZZqDpNh9H-jP5dUEYCo3ethwrNo',
    appId: '1:375461501131:ios:4dccb96bcd6b7022bfa34e',
    messagingSenderId: '375461501131',
    projectId: 'locallancers-app',
    storageBucket: 'locallancers-app.appspot.com',
    iosBundleId: 'com.example.locallancers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBvTNHZZqDpNh9H-jP5dUEYCo3ethwrNo',
    appId: '1:375461501131:ios:3bd6cc14ecb180b1bfa34e',
    messagingSenderId: '375461501131',
    projectId: 'locallancers-app',
    storageBucket: 'locallancers-app.appspot.com',
    iosBundleId: 'com.example.locallancers.RunnerTests',
  );
}
